### PR TITLE
fix(menu): alphabetical order for menu items

### PR DESCRIPTION
**Pull request by pesarkhobeee**
In oder to fix this problem:
https://github.com/Bonial-International-GmbH/MkRadar/issues/3
I am sending this patch

### CODE REVIEW

**Comment by nilsmull** [comment]
Maybe alphabetic ordering isn't the best option, I think the user would except to have the same order as in the config yaml file.

**Comment by pesarkhobeee** [comment]
Huuum then I should think how we can apply that because it is not as easy as this one I think

**Comment by pesarkhobeee** [comment]
Dear @nilsmull as you can see [here](https://github.com/Bonial-International-GmbH/MkRadar/blob/main/helpers/compiler.py#L68) we are creating the menu items based on the database rows and sadly by design there is no any option there to preserve the Item order based on the order of YAML configuration file:
https://github.com/Bonial-International-GmbH/MkRadar/blob/main/helpers/db_handler.py#L68
Also consider this fact, adding another column there is not enough because what if after the first compile user change the order of items in the YAML config file? Then we should detect and update all effected rows in the DB unless we make DB absolute and only use YAML file for everything! 
What I can suggest is  let's bring the stability and consistency via alphabetical order for now and in future if we really needed it we can plan for bigger changes :)

**Review by martinohmann — APPROVED** [review]
LGTM

**Pull request merged**
